services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=feedback
      - DB_PASSWORD=feedback
      - DB_NAME=feedback

  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    depends_on:
      - app

  db:
    image: postgres
    environment:
      - POSTGRES_USER=feedback
      - POSTGRES_PASSWORD=feedback
      - POSTGRES_DB=feedback
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: